# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: rocker/shiny-verse:latest
    environment:
      R_LIBS: ~/R/Library
    steps:
      # - restore_cache:
      #     keys:
      #       - r-pkg-cache-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
      #       - r-pkg-cache-
      - checkout
      - run:
          name: Inst⁄all package dependencies
          command: |
            mkdir -p ~/R/Library
            Rscript -e 'devtools::install_deps(dependencies = TRUE)'
      - run:
          name: Session info and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz --no-manual
      # - save_cache:
      #     key: r-pkg-cache-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
      #     paths:
      #       "~/R/Library"


